Спринт 10, initial
girisn/java-filmorate pull request #3
Opened 2023-05-14 18:48 UTC by girisn

ТЗ 10

2023-05-14 18:49 UTC, girisn commented
хм, я ожидала, что будут какие-то проверки, но ci/cd не отработал :(

2023-05-15 03:01 UTC, EugeneLenkevich requested changes
Привет, Наталия, спасибо за PR

В целом все отлично :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

2023-05-15 03:01 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/InMemoryFilmStorage.java
> +    public boolean containsId(Integer id) {
Предложу, кстати, еще вот такой метод, мжет с ним код нагляднее будет

public boolean isExist(Film film) {
// при желании ожно даже вот так
 return containsId(film.getId());
}

2023-05-15 07:27 UTC, EugeneLenkevich approved these changes
Вроде изменения по мелочи, зато эффект заметен
Теперь все отлично, спасибо :)

2023-05-15 09:43 UTC, girisn commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!filmStorage.contains(film)) {
ладно, в следующем ТЗ поправлю))

2023-05-15 09:43 UTC, merged

2023-05-15 11:33 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!filmStorage.contains(film)) {
В общем, основная мысль тут в том, чтобы использовать глаголы предметной области (и тем самым спрятать детали реализации) при написании бизнес-логики. Чтобы другой разработчик открыл код и смог читать его как связный текст, что-то вроде "если пользователь существует, то выкидываем ошибку иначе идем создавать запись в БД", вместо "проверяем ид в хранилище...". Вроде одно и то же, но разница в восприятии надеюсь что ощущается. Плюс, допустим, в будущем, мы решим что хотим идентифицировать пользователей по email или номеру телефона, какой код придеться переписывать, а какой нет  :)