ТЗ 11
girisn/java-filmorate pull request #5
Opened 2023-05-29 16:47 UTC by girisn

2023-05-29 16:56 UTC, girisn commented
Знаю, что замена private final LocalDate MIN_DATE на private LocalDate minimumDate - это очень тупо, но валидатор стиля предыдущий вариант не пропустил

2023-05-29 18:48 UTC, EugeneLenkevich requested changes
Привет, Наталия, спасибо за PR

В целом все отлично :)
1. Интересная иерархия классов, однако, когда вводишь иерархию надо подумать а стал ли наш код более простым или более гибким. Если нет то это может оказаться ненужным усложнением
2. Обрати внимание на имена переменных, постарайся не использовать цифры :)
3. Ну и запросы к СУБД не самая дешевая операция, их конечно бояться не надо, но лучше минимизировать, вытаскивать данные за их минимальное количество, ну и не тащить много записей, иначе модет память кончиться, это тоде стоит иметь в виду :)

2023-05-29 18:48 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public void removeFriend(@PathVariable("id") Long id1, @PathVariable("friendId") Long id2) {
Long id1,  Long id2

Давай все таки дадим нормальные имена переменным, по которым можно понять какие они данные содержат :)

2023-05-29 18:48 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/AbstractService.java
> +        return storage.create(data);
Может тут еше логирование уровня info или debug добавить, что то типа

log.debug("обновляем сущность: {}", data);

2023-05-29 18:48 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        storage.updateGenresByFilm(film);
Просто мысли вслух. А надо ли было создавать иерархию сервисов, сделало ли это код проще? :)
Иначе говоря, что проще понять, вот это
film = super.update(film);

или вот это

film = filmStorage.update(film) 

на подумать :)

2023-05-29 18:48 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        loadData(film);
Вот тут для каждого фильма мы идем в БД и вытаскиваем жанры отдельным запросом. 
Это не очень эффективно. А получится ли все данные вытьаскивать запросом ну или хотя бы жанры для всех фильмов вытаскивать за один запрос? :)

2023-05-29 18:48 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        films.sort(Comparator.comparing(Film::getLikesCount).reversed());
Сортировать лучше на уровне СУБД (в sql-запросе), она это делает гораздо эффективнее :)

2023-05-29 18:48 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        for (var friendId : friendsId) {
Опять таки, а не получится ли достать все за один запрос?

2023-05-29 18:48 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public List<User> getCommonFriends(Long id1, long id2) {
Long id1, long id2

Ох уж эти цифры в именах пременных, считается хорошей практикой этого избегать, может сильно путать, лучше дать нормальные имена переменным, отражающие их суть :)

2023-05-30 17:16 UTC, EugeneLenkevich approved these changes
Во, супер, спасибо :)

2023-06-02 12:54 UTC, merged